### ISSUE TITLE
Rails 5.1.3 with MongoID 6.2

### ISSUE THREAD

**Issue by SaimonL** [leandromoreira/mongoid-i18n#2]
For those who is using MongoID 6.2 you don't need this gem. 
MongoID 6.2 supports i18n natively. Its sad that this is not Documented anywhere in MongoID official website.

```yaml
en:
  mongoid:
    attributes:
      user:
        display_name: 'Display Name'
        first_name: 'First Name'
        last_name: 'Last Name'
        email: 'E-Mail'
        password: 'Password'

    errors:
      models:
        user:
          attributes:
            first_name:
              blank: 'First Name is required'

            email:
              blank: 'Email is required'
              taken: 'A duplicate user was found with this email address'
```
